version: "2"

services:
  ssr:
    image: orvice/tele-wechat-sync
    restart: always
    volumes:
      - ./log:/var/log
      - ./storage:/usr/src/app/storage
      - ./tgdata.db:/usr/src/app/plugins/eh_telegram_master/tgdata.db
    environment:
      - BOT_TOKEN=
      - ADMIN_ID=1
    container_name: tele-wechat
