version: "2"

services:
  ssr:
    image: orvice/tele-wechat-sync
    restart: always
    volumes:
      - ./log:/var/log
    environment:
      - BOT_TOKEN=
      - ADMIN_ID=1
    container_name: tele-wechat
